language: cpp

script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j4

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq mercurial
    - eval "${MATRIX_EVAL}"
    - wget http://ftp.us.debian.org/debian/pool/main/n/nauty/libnauty2_2.6r7+ds-1_amd64.deb
    - sudo dpkg -i libnauty2_2.6r7+ds-1_amd64.deb
    - sudo apt-get install -f
    - wget http://ftp.us.debian.org/debian/pool/main/n/nauty/libnauty2-dev_2.6r7+ds-1_amd64.deb
    - sudo dkpg -i libnauty2-dev_2.6r7+ds-1_amd64.deb
    - sudo apt-get install -f

