language: cpp

script:
    - mkdir build
    - cd build
    - cmake ..
    - make

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install mercurial
    - eval "${MATRIX_EVAL}"

